In [5]:
import numpy as np
import cv2

img = cv2.imread('img.jpg')
imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
ret, thresh = cv2.threshold(imgray, 127, 255, 0)
contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
print("Number of contours = " + str(len(contours)))
print(contours[0])

cv2.drawContours(img, contours, -1, (0, 255, 0), 3)
cv2.drawContours(imgray, contours, -1, (0, 255, 0), 3)

cv2.imshow('Image', img)
cv2.imshow('Image GRAY', imgray)
cv2.waitKey(0)
cv2.destroyAllWindows()

Number of contours = 56
[[[  0 405]]

 [[  0 406]]

 [[  0 407]]

 [[  0 408]]

 [[  0 409]]

 [[  0 410]]

 [[  0 411]]

 [[  0 412]]

 [[  1 412]]

 [[  2 412]]

 [[  3 412]]

 [[  4 412]]

 [[  5 412]]

 [[  6 412]]

 [[  7 412]]

 [[  8 412]]

 [[  9 412]]

 [[ 10 412]]

 [[ 11 412]]

 [[ 12 412]]

 [[ 13 412]]

 [[ 14 412]]

 [[ 15 412]]

 [[ 16 412]]

 [[ 17 412]]

 [[ 18 412]]

 [[ 17 411]]

 [[ 16 410]]

 [[ 15 410]]

 [[ 14 410]]

 [[ 13 410]]

 [[ 12 409]]

 [[ 11 409]]

 [[ 10 409]]

 [[  9 409]]

 [[  8 408]]

 [[  7 408]]

 [[  6 408]]

 [[  5 407]]

 [[  4 407]]

 [[  3 407]]

 [[  2 406]]

 [[  1 406]]]
