In [2]:
import cv2
import numpy as np
img = cv2.imread("img.jpg")
grey_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
template = cv2.imread("imgg2.jpg", 0)
w, h = template.shape[::-1]

res = cv2.matchTemplate(grey_img, template, cv2.TM_CCORR_NORMED )
print(res)
threshold = 0.999;
loc = np.where(res >= threshold)
print(loc)
for pt in zip(*loc[::-1]):
    cv2.rectangle(img, pt, (pt[0] + w, pt[1] + h), (0, 0, 255), 2)

cv2.imshow("img", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[0.7868854  0.78534067 0.78385496 ... 0.7876931  0.7909889  0.7943679 ]
 [0.785999   0.78441316 0.7829031  ... 0.7869093  0.7902112  0.79359627]
 [0.7851305  0.7835031  0.7819605  ... 0.7861831  0.789487   0.7928728 ]
 ...
 [0.83954555 0.8393377  0.8392373  ... 0.84078485 0.8405419  0.84017307]
 [0.84029037 0.8400717  0.83994466 ... 0.84082824 0.8406225  0.8402801 ]
 [0.8409676  0.84073955 0.8405834  ... 0.8408989  0.84073734 0.8404349 ]]
(array([41], dtype=int64), array([107], dtype=int64))
